[package]
name = "blazingly_fast"
version = "1.0.2"
edition = "2021"
description = "Blazingly fast bogosort because Rust."
license = "Apache-2.0"
repository = "https://github.com/golmschenk/blazingly_fast"

[dependencies]
rand = "0.8.5"
